name: Deploy AWS Infrastructure with CloudFormation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file infrastructure/cloudformation-template.yml \
          --stack-name cqrs-stack \
          --capabilities CAPABILITY_NAMED_IAM
